fix pesign calls

diff --git a/pesign-repackage.spec.in b/pesign-repackage.spec.in
--- a/pesign-repackage.spec.in
+++ b/pesign-repackage.spec.in
@@ -80,11 +80,10 @@ else
 	cert=/usr/lib/rpm/pesign-cert.x509
 fi
 mkdir nss-db
-echo nss-db/password
 nss_db=$PWD/nss-db
-certutil -N -f "$nss_db/password" -d "$nss_db"
-# FIXME
-certutil -A -f "$nss_db/password" -d "$nss_db" -n cert -t P,P,P -i "$cert" || :
+echo foofoofoo > "$nss_db/passwd"
+certutil -N -d "$nss_db" -f "$nss_db/passwd"
+certutil -A -d "$nss_db" -n cert -t CT,CT,CT -i "$cert"
 
 sigs=($(find -type f -name '*.sig'))
 for sig in "${sigs[@]}"; do
@@ -96,10 +95,19 @@ for sig in "${sigs[@]}"; do
 	./lib/firmware/*.sig)
 		/usr/lib/rpm/kernel-sign-file -f -s "$sig" sha256 "$cert" "$f"
 		;;
-	./boot/* | *.efi)
-		# FIXME
-		pesign -n "$nss_db" -c cert -i "$f" -o "$f.tmp" -m "$sig" || :
-		mv "$f.tmp" "$f" || :
+	./boot/* | *.efi.sig)
+		infile=${sig%.sig}
+		cpio -i --to-stdout ${infile#./} <%_sourcedir/@NAME@.cpio.rsasign > ${infile}.sattrs
+		test -s ${infile}.sattrs || exit 1
+		ohash=$(pesign -n "$nss_db" -h -i "$f")
+		pesign -n "$nss_db" -c cert -i "$f" -o "$f.tmp" -d sha256 -I "${infile}.sattrs" -R "$sig"
+		rm -f "${infile}.sattrs"
+		mv "$f.tmp" "$f"
+		nhash=$(pesign -n "$nss_db" -h -i "$f")
+		if test "$ohash" != "$nhash" ; then
+		    echo "hash mismatch error: $ohash $nhash"
+		    exit 1
+		fi
 		;;
 	*)
 		echo "Warning: unhandled signature: $sig" >&2
